apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-hpa
  namespace: desafio-devops
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu # foi utilizado a cpu como métrica para funcionamento do HPA
      target:
        averageUtilization: 70 # ao chegar em 70% do limite em CPU, um node será acrescentado
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express
